# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .build

on:
  push:
    branches: "*" 
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: "*"
    paths-ignore:
      - '**/README.md'

env:
  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Publish
      run: dotnet publish -c Release -o release -p:PublishSingleFile=true --self-contained false
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: GithubActionsSandbox-${{matrix.os}}
        path: ${{ github.workspace }}/github_actions_sandbox/github_actions_sandbox/release//GithubActionsSandbox*
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        artifacts: GithubActionsSandbox-${{matrix.os}}
        body: This is dev release, use at your own risk
        name: GithubActionsSandbox 
        prerelease: true
        tag: latest-dev
